yapf -i bgcvaltools/AOU.py
yapf -i bgcvaltools/C2Chl.py
yapf -i bgcvaltools/communitystructure.py
yapf -i bgcvaltools/comstrucFit.py
yapf -i bgcvaltools/dataset.py
yapf -i bgcvaltools/downloadFromMass.py
yapf -i bgcvaltools/linkTwoJobs.py
yapf -i bgcvaltools/makeEORCAmasks.py
yapf -i bgcvaltools/makeMask.py
yapf -i bgcvaltools/mergeMonthlyFiles.py
yapf -i bgcvaltools/pftnames.py
yapf -i bgcvaltools/prepareERSEMyear.py
yapf -i bgcvaltools/prepareMEDUSAyear.py
yapf -i bgcvaltools/regionMapLegend.py
yapf -i bgcvaltools/removeMaskFromshelve.py
yapf -i bgcvaltools/robust.py
yapf -i bgcvaltools/RobustStatistics.py
yapf -i bgcvaltools/StatsDiagram.py
yapf -i bgcvaltools/unbiasedSymmetricMetrics.py
yapf -i bgcvaltools/viridis.py
